-- MySQL Script generated by MySQL Workbench
-- 03/20/17 11:22:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema titan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema titan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titan` DEFAULT CHARACTER SET utf8 ;
USE `titan` ;

-- -----------------------------------------------------
-- Table `titan`.`daily_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`daily_report` ;

CREATE TABLE IF NOT EXISTS `titan`.`daily_report` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `operator` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '运营人员',
  `area_id` INT(11) NOT NULL DEFAULT '0' COMMENT '区域id',
  `area` VARCHAR(4) NOT NULL DEFAULT '' COMMENT '区域',
  `agent_id` INT(11) NOT NULL DEFAULT '0' COMMENT '代理商id',
  `agent` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '代理商',
  `customer` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户',
  `industry` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '行业类型',
  `nearly_consumed` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '近7天日均消耗',
  `nearly_click` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '近7天的点击数',
  `nearly_exposure` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '近7天的曝光量',
  `yesterday_budget` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '上一天客户预算',
  `yesterday_consume` DECIMAL(16,2) NOT NULL DEFAULT '0.00' COMMENT '上一天客户消耗',
  `yesterday_optimize` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '上一天账户优化情况',
  `problem` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '账户优化中待解决的问题',
  `today_optimize` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '当天的优化计划',
  `support` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '需要的支持',
  `feedback` VARCHAR(500) NOT NULL DEFAULT '',
  `kpi` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'kpi说明',
  `kpi_actual` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'kpi实际完成情况',
  `conversion_cost` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '转化成本',
  `operation_state` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '当前运营状态',
  `otherinfo` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '其他信息',
  `record_state` INT(4) NOT NULL DEFAULT '1',
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COMMENT = '针对运营人员的日报功能表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`label` ;

CREATE TABLE IF NOT EXISTS `titan`.`label` (
  `label_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '标签ID',
  `label_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '标签名称',
  `label_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '标签类型',
  `label_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '标签状态（有效，无效）',
  `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '标签描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`label_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '标签表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`permission` ;

CREATE TABLE IF NOT EXISTS `titan`.`permission` (
  `permission_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '权限ID',
  `permission_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '权限名称',
  `permission_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '权限类型（举例：将权限按模块分类）',
  `permission_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '权限状态（有效，无效）',
  `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = '权限表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`product` ;

CREATE TABLE IF NOT EXISTS `titan`.`product` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '产品ID',
  `product_name` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '产品名称',
  `product_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '产品类型（cpd，cpc，cpm）',
  `product_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '产品状态',
  `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '产品描述',
  `begin_time` TIMESTAMP NOT NULL DEFAULT '1976-01-01 00:00:00' COMMENT '产品启动时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '产品表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`role` ;

CREATE TABLE IF NOT EXISTS `titan`.`role` (
  `role_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `role_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '角色名称',
  `role_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '角色类型（类似超级角色，普通角色，弃用角色；分等级用）',
  `role_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '角色状态',
  `description` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '描述',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '角色表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `titan`.`role_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `role_id` INT(11) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `permission_id` INT(11) NOT NULL DEFAULT '0' COMMENT '权限ID',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '此记录的状态（已弃用，有效等等）',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '角色权限映射表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user` ;

CREATE TABLE IF NOT EXISTS `titan`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `user_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户名称（默认为注册邮箱前缀）',
  `sso_id` INT(10) NOT NULL DEFAULT '0' COMMENT '新浪通行证唯一ID',
  `user_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '用户状态（已授权，未授权）',
  `auth_time` TIMESTAMP NOT NULL DEFAULT '1976-01-01 00:00:00' COMMENT '用户认证新浪通行证时间戳',
  `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '姓名',
  `identity_card` VARCHAR(18) NOT NULL DEFAULT '' COMMENT '身份证号',
  `phone` VARCHAR(12) NOT NULL DEFAULT '' COMMENT '电话号',
  `agent_id` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '用户所属代理商ID',
  `agent_name` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '用户所属代理商名称',
  `description` VARCHAR(256) NOT NULL DEFAULT '' COMMENT '自我描述',
  `graduration_time` YEAR(4) NOT NULL DEFAULT '1990' COMMENT '毕业时间',
  `education` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '学历',
  `univercity` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '最后毕业的院校名称',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `icon` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '用户头像(/local/icon/default.jpg)',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user_label`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user_label` ;

CREATE TABLE IF NOT EXISTS `titan`.`user_label` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `label_id` INT(11) NOT NULL DEFAULT '0' COMMENT '标签ID',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '此记录的状态',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户标签映射表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user_mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user_mail` ;

CREATE TABLE IF NOT EXISTS `titan`.`user_mail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `mail` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户登录e-mail',
  `pwd` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户登录密码',
  `mail_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '邮件类型（工作，个人，社交，已弃用等等)',
  `salt` VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'pwd key',
  `token` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'token',
  `token_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'token类型（有效，已弃用等）',
  `token_gen_time` TIMESTAMP NOT NULL DEFAULT '1976-01-01 00:00:00' COMMENT 'token生成时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8
COMMENT = '邮件表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user_phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user_phone` ;

CREATE TABLE IF NOT EXISTS `titan`.`user_phone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `phone` VARCHAR(12) NOT NULL DEFAULT '' COMMENT '电话号',
  `pwd` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `phone_type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '此电话类型（有效，已弃用，个人，工作等）',
  `salt` VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'pwd key',
  `token` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'token',
  `token_state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'token类型（有效，已弃用等）',
  `token_gen_time` TIMESTAMP NOT NULL DEFAULT '1976-01-01 00:00:00' COMMENT 'token生成时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '手机号表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user_product` ;

CREATE TABLE IF NOT EXISTS `titan`.`user_product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `product_id` INT(11) NOT NULL DEFAULT '0' COMMENT '产品ID',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '此记录的状态（有效，已弃用等）',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户产品映射表'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `titan`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `titan`.`user_role` ;

CREATE TABLE IF NOT EXISTS `titan`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` INT(11) NOT NULL DEFAULT '0' COMMENT '用户ID',
  `role_id` INT(11) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `state` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '此记录的状态（有效，已弃用等）',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '用户角色映射表'
ROW_FORMAT = COMPACT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
